apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: VITE_SUPABASE_URL
          value: "{{ .Values.VITE_SUPABASE_URL }}"
        - name: VITE_SUPABASE_KEY
          value: "{{ .Values.VITE_SUPABASE_KEY }}"
        - name: VITE_GAMES_SERVICE_URL
          value: "{{ .Values.VITE_GAMES_SERVICE_URL }}"
