apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kofolmarko/ob-kavici-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_GAMES_SERVICE_URL
              value: "http://games-service.default.svc.cluster.local"
          envFrom:
            - secretRef:
                name: frontend-secrets
