apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kofolmarko/frontend:<IMAGE_TAG>  # Placeholder for dynamic tag
          ports:
            - containerPort: 80
          env:
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_SUPABASE_URL
            - name: VITE_SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_SUPABASE_KEY
            - name: VITE_GAMES_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: VITE_GAMES_SERVICE_URL