replicaCount: 1

image:
  repository: kofolmarko/ob-kavici-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: www.ob-kavici.si
