name: Deploy Frontend to AKS

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd ob-kavici
          npm install -g pnpm
          pnpm install

      - name: Run tests
        run: pnpm test

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker build --no-cache \
            --build-arg VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --build-arg VITE_GAMES_SERVICE_URL=http://api.ob-kavici.si \
            -t kofolmarko/ob-kavici-frontend:$TAG \
            -t kofolmarko/ob-kavici-frontend:latest .
          docker push kofolmarko/ob-kavici-frontend:$TAG
          docker push kofolmarko/ob-kavici-frontend:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Frontend to AKS with Helm
        run: |
          TAG=$(git rev-parse --short HEAD)
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            ENV="prod"
          elif [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            ENV="dev"
          else
            echo "Unsupported branch. Exiting."
            exit 1
          fi

          helm upgrade --install frontend ./charts \
            --values values.${ENV}.yaml \
            --set image.tag=$TAG \
            --set VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --set VITE_SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --set VITE_GAMES_SERVICE_URL=http://api.ob-kavici.si


      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/frontend
