name: Deploy Frontend to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current branch and files
        run: |
          git branch
          git log -1
          ls -al

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg VITE_GAMES_SERVICE_URL="http://games-service.default.svc.cluster.local" -t kofolmarko/frontend:latest .
          docker push kofolmarko/frontend:latest

      - name: Set up Kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

      - name: Use context
        run: kubectl config use-context obKaviciAKS

      - name: Apply Kubernetes Secret
        run: |
          kubectl create secret generic frontend-secrets \
          --from-literal=VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --from-literal=VITE_SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Frontend to AKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/frontend
